#!/usr/bin/env bash

xrandr \
    --output HDMI-0 \
        --mode 1920x1080 \
        --primary \
        --auto \
    --output eDP-1-1 \
        --mode 1920x1080 \
        --right-of HDMI-0 \
        --auto

~/.fehbg

xscreensaver -no-splash &
