#!/usr/bin/env bash

xrdb -merge ~/.Xresources

~/.screenlayout/vusec-desk.sh

~/.fehbg

xscreensaver -no-splash &

setxkbmap -option 'compose:ralt'

mkdir -p $HOME/.log

nohup dunst > $HOME/.log/dunst.log &

