#!/usr/bin/env bash

xrdb -merge ~/.Xresources

xrandr \
    --output HDMI-0 \
        --mode 1920x1080 \
        --primary \
        --auto \
    --output eDP-1-1 \
        --mode 1920x1080 \
        --right-of HDMI-0 \
        --auto

~/.fehbg

xscreensaver -no-splash &

mkdir -p $HOME/.log

nohup /usr/lib/notification-daemon/notification-daemon > $HOME/.log/notification-daemon.log &
